#!/bin/sh

GENERATORS="js css"

TEMPLATE_DIR="$MY_DIR/templates"

DIR="$BASE_DIR/$MODULE_BASE"

# Create the view directory and go there
mkdir -p "$DIR"
pushd "$DIR" >> /dev/null

export CSS_NAME="${MODULE/\./-}"
