#!/bin/sh

FILE="$TDIR/$MODULE.html"

fail_if_exists "$FILE"

# Create dir
mkdir -p "$TDIR"

PLUGIN_ID="$MODULE"
if [[ "$MODULE_BASE" != "" ]]; then
	PLUGIN_ID="$MODULE_BASE/$PLUGIN_ID"
fi
export PLUGIN_ID

export REL_WIRE_DIR=`relpath "$BASE_DIR" "$TDIR"`

log_file "$MODULE_BASE/$MODULE.html"
template "$MY_DIR/templates/test.html" > "$FILE"
