#!/bin/sh

DIR="${MODULE_PATH//\.//}"
DEST="$MINE_GEN_BASE_DIR/$DIR"
SRC=${1:-.}

if [[ -d "$SRC" ]]; then
	TYPE="localInstall"
else
	TYPE="githubInstall"
fi

function localInstall {
	mkdir -p "$1"
	rsync -a "$2/" "$1/"
}

function githubInstall {
	local TMP="/tmp/$ME.$$"
	git clone "$2" "$TMP"
	\rm -rf "$TMP/.git*"
	localInstall "$1" "$TMP"
}

fail_if_exists $1
log_dir "$DEST"

"$TYPE" "$DEST" "$SRC"

msg "$MODULE_PATH installed"